### ISSUE TITLE
Permettre de diminuer/cacher le popin des filtres

### ISSUE THREAD

**Issue by overflorian** [overflorian/panneauxbiche#12]
qui prend toute la place sur un écran mobile :
![screenshot_2015-06-14-15-59-20](https://cloud.githubusercontent.com/assets/11553211/8148829/8a68171c-12ae-11e5-9eee-467016e410ca.png)

Avec un petit bouton ou tout autre moyen

**Comment by Marcussacapuces91** [comment]
Done ! but may be not in sources

**Comment by overflorian** [comment]
<3
