### ISSUE TITLE
Faire un joli texte dans la langue de ton choix pour le panneau d'information

### ISSUE THREAD

**Issue by Marcussacapuces91** [overflorian/panneauxbiche#3]
On peut tout faire en html et mettre le résultat ici même, je le copierais dans le fichier index.htm

**Comment by Marcussacapuces91** [comment]
Là j'ai mis le texte du GitHub, mais on peut changer hein

**Comment by overflorian** [comment]
Ma petite proposition ici : https://github.com/overflorian/panneauxbiche/pull/11
C'est pas encore dingue mais ça passe en temporaire.
