### ISSUE TITLE
add hazard=crocodile

### ISSUE THREAD

**Issue by overflorian** [overflorian/panneauxbiche#5]
I just added a hazard=crocodile tag here: https://www.openstreetmap.org/way/172625595
Please make it appear on the map! Thanks

**Comment by Marcussacapuces91** [comment]
Done ! corrected & commited in https://github.com/overflorian/panneauxbiche/commit/4de7d1854ec230a8ae3c73fd8368bc49a9f6112b

**Comment by overflorian** [comment]
<3
