### ISSUE TITLE
Permettre de sélectionner le type de panneau à afficher

### ISSUE THREAD

**Issue by overflorian** [overflorian/panneauxbiche#6]
Créer des filtres sélectionnables avec le type de danger.
Choisir parmi les différentes idées de filtres ci-dessous :
-Uniquement 2 filtres génériques : 1. Animaux 2. Humains
-Filtres pour chaque espèce : 1. Biches 2. Vaches 3. Moutons 4. Cavaliers 5. Crocodiles 6. Rênes / élans 7. Requins 8. Enfants 9. Cyclistes 10. Passage piéton 11. Robots ...

Afficher uniquement les panneaux de traversée d'animaux sauvages de tout type par défaut.

**Comment by Marcussacapuces91** [comment]
Je vais faire ça en multi-couche : 1 couche par espèce. Et après on verra comment les sélectionner un par un pour plusieurs à la fois.

**Comment by overflorian** [comment]
Cela me parait la meilleure solution, merci.
