### ISSUE TITLE
Poser un Piwik

### ISSUE THREAD

**Issue by overflorian** [overflorian/panneauxbiche#8]
pour les stats

**Comment by Marcussacapuces91** [comment]
OK, faudra un accès MySQL. Sinon un autre produit plus light, chez ovh il y
a des outils pré-installés :
https://www.ovh.com/fr/g1344.statistiques-et-logs

**Comment by overflorian** [comment]
On peut en effet se contenter de ça pour l'instant, merci pour l'info.

**Comment by Marcussacapuces91** [comment]
Si t'es ok tu ferme l'issue ?
