### ISSUE TITLE
ajouter hazard=robot

### ISSUE THREAD

**Issue by overflorian** [overflorian/panneauxbiche#9]
Le plus essentiel de tous les risques enfin cartographié !
J'ai rajouté les fablabs, le nouveau bureau de recherche de Facebook à Paris, l'INRIA ... je travaille sur la suite.
Pas mal hein ??

**Comment by Marcussacapuces91** [comment]
tu me mets une image 60*53 d'un panneau robot ?

**Comment by overflorian** [comment]
J'ai cherché un beau panneau hier mais j'ai pas trouvé. J'y travaille.

**Comment by Marcussacapuces91** [comment]
j'ai mis un panneau danger simple en attendant sur http://test.sibert.fr, je sais c'est black listé

**Comment by overflorian** [comment]
Le résultat depuis mon téléphone est convaincant. Je vais trouver un panneau de préférence jaune entouré de noir comme pour les crocos

**Comment by overflorian** [comment]
Alors tu penses quoi de mon robot ? :)
![robot](https://cloud.githubusercontent.com/assets/11553211/8114453/ee8191ec-1074-11e5-94d4-4af22a199039.png)
Je l'ai uploadé en FTP dans le dossier images.

Si cela te convient il faudrait rajouter la licence suivante dans le ABOUT du coup stp :
<a href="http://fr.freepik.com/vecteurs-libre/silhouettes-collection-de-robots-de-vecteur_714902.htm">Logo de robot conçu par Freepik</a>
